### ISSUE TITLE
CRUD Autores

### ISSUE THREAD

**Issue by yessermiranda13** [jamescito/SIRAP#2]
## Problema encontrado
#1 aplicó las ediciones sobre autores, aun falta eliminar, así que es necesario la funcionalidad de editar 

## Modificaciones esperadas
 * Eliminar un autor desde la tabla del index
 * Es necesario hacer el borrado en el controlador de Autores en el método destroy

## Especificaciones esperadas
Es recomendable que describa bien los commit realizados y los cambios generados, comandos que se se deben aplicar y acciones a realizar sobre esos cambios
Es necesario documentar en [fichero principal](https://github.com/jamescito/SIRAP/blob/main/README.md)

**Comment by yessermiranda13** [comment]
@jamescito el pull request #6 cumple con esto

**Comment by jamescito** [comment]
# Reabriendo una propuesta para verificar

**Comment by jamescito** [comment]
Cerrando issue

**Comment by yessermiranda13** [comment]
Problema cerrado con #6

**Comment by jamescito** [comment]
@yessermiranda13 Entiendo que el #6 esta finalizado

**Comment by yessermiranda13** [comment]
@jamescito Confirmación de cierre terminada
