### ISSUE TITLE
CRUD Editoriales

### ISSUE THREAD

**Issue by yessermiranda13** [jamescito/SIRAP#3]
# Característica CRUD editoriales
## Problemas encontrados
```mysql
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'inatec.editorials' doesn't exist (SQL: select * from editorials)
```
## Cambios requeridos
 * Es necesario revisar el controlador y cambiar el nombre de la tabla en la consulta
 * Crear la diferentes vistas para manipular el CRUD en laravel
 * Realizar todas las operaciones de manipulación de tablas de base de datos usando las vistas

## Resultados esperados
Es necesario que cree un commit con detalles sobre lo realizado no importando el tamaño del nombre

**Comment by Eliezer-Ochoa** [comment]
El #7 responde a una característica del CRUD

**Comment by yessermiranda13** [comment]
El #10 resuelve este caso

**Comment by yessermiranda13** [comment]
@Eliezer-Ochoa  Resolver problema en la funcionalidad editar editoriales

**Comment by Eliezer-Ochoa** [comment]
@yessermiranda13 Porque si ami no me da error

**Comment by jamescito** [comment]
@Eliezer-Ochoa  la carpetas que contiene las vista editoriales está en mayúscula y en el código la manda a llamar en minúscula, por tanto en Windows es posible que no se detecte el error, pero en Linux el error si se nota, entonces #3 y #10  están a espera a que le de solución usted.
